-- AlterTable DailyMetric: add channel revenue and order fields
ALTER TABLE "DailyMetric" ADD COLUMN IF NOT EXISTS "liveStreamRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DailyMetric" ADD COLUMN IF NOT EXISTS "shortVideoRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DailyMetric" ADD COLUMN IF NOT EXISTS "mallRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DailyMetric" ADD COLUMN IF NOT EXISTS "influencerRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DailyMetric" ADD COLUMN IF NOT EXISTS "liveStreamOrders" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DailyMetric" ADD COLUMN IF NOT EXISTS "shortVideoOrders" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DailyMetric" ADD COLUMN IF NOT EXISTS "mallOrders" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DailyMetric" ADD COLUMN IF NOT EXISTS "influencerOrders" INTEGER NOT NULL DEFAULT 0;

-- AlterTable ShopSettings: add annual revenue goal
ALTER TABLE "ShopSettings" ADD COLUMN IF NOT EXISTS "annualRevenueGoal" DOUBLE PRECISION NOT NULL DEFAULT 120000;
